"""
3-Tier PDF generator:
  Tier 1 — CONFIRMED  (score ≥ 70): High relevance, recommended papers
  Tier 2 — SUSPICIOUS (score 40-69): Possible relevance, review manually
  Tier 3 — REJECTED   (score < 40): Searched but not relevant
"""
import os, re
from fpdf import FPDF
from datetime import datetime
from models.schemas import PDFReports

OUTPUT_DIR = "./data/pdfs"
os.makedirs(OUTPUT_DIR, exist_ok=True)

_TIER_CONFIG = {
    "confirmed":  {"label": "CONFIRMED - High Relevance",      "color": (14, 128, 70),  "accent": (20, 180, 100)},
    "suspicious": {"label": "SUSPICIOUS - Possible Relevance", "color": (180, 120, 0),  "accent": (220, 160, 0)},
    "rejected":   {"label": "REJECTED - Below Threshold",      "color": (160, 30, 30),  "accent": (200, 60, 60)},
}

def _safe(text: str, max_chars: int = 50) -> str:
    return re.sub(r"[^\w\s-]", "", text)[:max_chars].strip().replace(" ", "_")

def _wrap(text: str, max_chars: int = 95) -> list[str]:
    words = text.split()
    lines, cur = [], ""
    for w in words:
        if len(cur) + len(w) + 1 <= max_chars:
            cur = f"{cur} {w}".strip()
        else:
            if cur:
                lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines

def _safe_str(val, default="") -> str:
    try:
        text = str(val or default)
        # Replace common Unicode chars that Helvetica can't render
        replacements = {
            "\u2014": "--", "\u2013": "-", "\u2012": "-",  # em/en dashes
            "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',  # smart quotes
            "\u2026": "...", "\u00b0": " deg", "\u00b1": "+/-",
            "\u03b1": "alpha", "\u03b2": "beta", "\u03b3": "gamma",
            "\u00e9": "e", "\u00e8": "e", "\u00ea": "e", "\u00fc": "u",
            "\u00e4": "a", "\u00f6": "o", "\u00c4": "A", "\u00d6": "O",
        }
        for char, replacement in replacements.items():
            text = text.replace(char, replacement)
        # Strip any remaining non-latin1 chars
        return text.encode("latin-1", errors="replace").decode("latin-1")
    except Exception:
        return default

class _PDF(FPDF):
    def __init__(self, tier: str, query: str, generated_terms: list[str]):
        super().__init__()
        self.tier = tier
        self.query = query
        self.generated_terms = generated_terms
        self.cfg = _TIER_CONFIG[tier]
        self.set_auto_page_break(auto=True, margin=18)

    def cell(self, *args, **kwargs):
        if "text" in kwargs:
            kwargs["text"] = _safe_str(kwargs["text"])
        elif len(args) >= 3:
            args = list(args)
            args[2] = _safe_str(args[2])
        return super().cell(*args, **kwargs)

    def multi_cell(self, *args, **kwargs):
        if "text" in kwargs:
            kwargs["text"] = _safe_str(kwargs["text"])
        elif len(args) >= 3:
            args = list(args)
            args[2] = _safe_str(args[2])
        return super().multi_cell(*args, **kwargs)

    def header(self):
        r, g, b = self.cfg["color"]
        self.set_fill_color(r, g, b)
        self.rect(0, 0, 210, 22, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 13)
        self.set_xy(8, 4)
        self.cell(0, 8, "Research Paper Finder", ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_xy(8, 13)
        self.cell(0, 6, self.cfg["label"], ln=True)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, f"Page {self.page_no()} | Generated by Research Paper Finder", align="C")

def _add_cover_page(pdf: _PDF, total: int):
    pdf.add_page()
    pdf.ln(10)
    r, g, b = pdf.cfg["color"]
    # Tier badge
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 14, f"  {pdf.cfg['label']}", fill=True, ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)
    # Meta info
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 6, f"Search Query: {pdf.query[:100]}", ln=True)
    pdf.cell(0, 6, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", ln=True)
    pdf.cell(0, 6, f"Total Papers in this Report: {total}", ln=True)
    pdf.ln(4)
    # Search terms used
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 6, "AI-Generated Search Terms:", ln=True)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(80, 80, 80)
    for line in _wrap(", ".join(pdf.generated_terms), 110):
        pdf.cell(0, 5, line, ln=True)
    pdf.ln(6)
    # Score range explanation per tier
    tier_desc = {
        "confirmed":  "These papers scored 70–100 for relevance. Highly recommended for reading.",
        "suspicious": "These papers scored 40–69. Potentially relevant — review abstracts manually.",
        "rejected":   "These papers scored below 40. Returned by keyword search but assessed as not relevant.",
    }
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(60, 60, 60)
    pdf.multi_cell(0, 5, tier_desc[pdf.tier], border=1, fill=True)

def _add_paper_page(pdf: _PDF, paper: dict, rank: int):
    pdf.add_page()
    score = paper.get("relevance_score", 0)
    r, g, b = pdf.cfg["color"]

    # Rank + score banner
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_xy(10, 25)
    pdf.cell(0, 9, f"  #{rank}  Score: {score:.0f}/100  |  Source: {_safe_str(paper.get('source'))}", fill=True, ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Title
    pdf.set_font("Helvetica", "B", 13)
    for line in _wrap(_safe_str(paper.get("title"), "Untitled"), 88):
        pdf.cell(0, 7, line, ln=True)
    pdf.ln(2)

    # Authors & metadata
    authors = paper.get("authors") or []
    author_str = ", ".join(authors[:5])
    if len(authors) > 5:
        author_str += f" +{len(authors)-5} more"
    year = _safe_str(paper.get("year"), "Unknown year")
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, f"Authors: {author_str or 'Unknown'}", ln=True)
    pdf.cell(0, 5, f"Year: {year}", ln=True)

    doi = paper.get("doi")
    if doi:
        pdf.cell(0, 5, f"DOI: {doi}", ln=True)
    url = paper.get("url")
    if url:
        pdf.set_text_color(0, 70, 180)
        pdf.cell(0, 5, f"URL: {str(url)[:90]}", ln=True)
    pdf_link = paper.get("pdf_url")
    if pdf_link:
        pdf.set_text_color(0, 130, 60)
        pdf.cell(0, 5, f"PDF: {str(pdf_link)[:90]}", ln=True)

    # Divider
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)
    pdf.set_draw_color(180, 180, 180)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    # Abstract
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "Abstract", ln=True)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(40, 40, 40)
    abstract = _safe_str(paper.get("abstract"), "No abstract available.")[:1500]
    for line in _wrap(abstract, 100):
        pdf.cell(0, 4.5, line, ln=True)
    pdf.ln(4)

    # LLM reasoning
    reasoning = _safe_str(paper.get("relevance_reasoning"))
    if reasoning:
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 5, "LLM Relevance Assessment", ln=True)
        pdf.set_font("Helvetica", "I", 8.5)
        pdf.set_text_color(60, 60, 60)
        for line in _wrap(reasoning, 100):
            pdf.cell(0, 4.5, line, ln=True)

async def _write_pdf(tier: str, query: str, generated_terms: list[str], papers: list[dict]) -> str | None:
    if not papers:
        return None
    pdf = _PDF(tier, query, generated_terms)
    _add_cover_page(pdf, len(papers))
    for i, paper in enumerate(papers, 1):
        _add_paper_page(pdf, paper, i)

    q_slug = _safe(query)
    filename = f"{tier}_{q_slug}_{datetime.utcnow().strftime('%Y%m%d_%H%M')}.pdf"
    filepath = os.path.join(OUTPUT_DIR, filename)
    pdf.output(filepath)
    return filename

async def generate_tiered_pdfs(
    query: str,
    generated: dict,
    confirmed: list[dict],
    suspicious: list[dict],
    rejected: list[dict],
) -> "PDFReports":
    from models.schemas import PDFReports
    terms = (
        generated.get("terms_general", []) +
        generated.get("terms_arxiv", []) +
        generated.get("terms_pubmed", [])
    )[:12]

    c = await _write_pdf("confirmed", query, terms, confirmed)
    s = await _write_pdf("suspicious", query, terms, suspicious)
    r = await _write_pdf("rejected", query, terms, rejected)
    return PDFReports(confirmed=c, suspicious=s, rejected=r)
